### ISSUE TITLE
Autoscroll problem.

### ISSUE THREAD

**Issue by BonesMcGinty** [rametta/quantor#1]
When you click on a link in the left nav, the page scrolls to the anchor. the only problem is that the top nav covers the header of the section.

**Comment by rametta** [comment]
Have you tried turning it off and then back on again?

**Comment by rametta** [comment]
Fixed in this commit: https://github.com/rametta/quantor/commit/188623f98897874c48bba2e6210f40b498515122#diff-d84e57710389df4247938723fb6c7aa3R183
