### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by BonesMcGinty** [rametta/quantor#2]
It would be nice to see default values for params that are displayed.
Maybe different branches of required params based on another param as well?

**Comment by rametta** [comment]
Default is good idea.
The second one would mean it's still optional. Might just be better to explain it in the description for each param if it depends on something else.

**Comment by rametta** [comment]
closed by commit https://github.com/rametta/quantor/commit/45d92508ecbcf5160d27dfd4d757ae7ca3d7d0cb
