### ISSUE TITLE
Write some unit tests

### ISSUE THREAD

**Issue by rametta** [rametta/quantor#6]
This would be very helpful for the index.js file that has all the logic. 
Preferably with Jest and produces a coverage report.

**Comment by camdenbrown-zz** [comment]
I'll get Jest running with a coverage report, so anyone can start testing. Then, I'll see if I can test the index.js file you indicated.

**Comment by rametta** [comment]
Thanks @camdenbrown ! I merged your pr #8 . Now we just need some tests from anybody who wants to give it a shot :100:
